### PR TITLE
Modified automator app

### PR DESCRIPTION
**Pull request by jwwolff**
Changed the terminal code that the automator app uses to allow for the ckan.exe to be anywhere on the computer and not limited to the downloads folder.

### CODE REVIEW

**Comment by Maxzhao1999** [comment]
somehow on mine this does not open the gui but the command line and shows the below


Very nice icon btw.

**Comment by Maxzhao1999** [comment]
Added to the new release, thanks!

**Comment by jwwolff** [comment]
np.  I don't know why it would pull up the command line version of ckan.exe if you type in 'mono $(mdfind ckan.exe)' into the terminal does it still come up as the command line version?

**Comment by Maxzhao1999** [comment]
Yeah it does even if it's typed in manually, but on the new release I just added a line to open the gui in the command line so it's fine now, thanks for your time! The icon again looks amazing👍

**Pull request closed without merging**
